// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Surasshu.Data;

#nullable disable

namespace Surasshu.Migrations
{
    [DbContext(typeof(SurasshuContext))]
    partial class SurasshuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Surasshu.Areas.Identity.Data.SurasshuUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WarriorFiveId")
                        .HasColumnType("int");

                    b.Property<int?>("WarriorFourId")
                        .HasColumnType("int");

                    b.Property<int?>("WarriorOneId")
                        .HasColumnType("int");

                    b.Property<int?>("WarriorThreeId")
                        .HasColumnType("int");

                    b.Property<int?>("WarriorTwoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Surasshu.Models.OwnedQuirk", b =>
                {
                    b.Property<int>("OwnedQuirkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnedQuirkId"), 1L, 1);

                    b.Property<int>("QuirkId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OwnedQuirkId");

                    b.ToTable("OwnedQuirks");
                });

            modelBuilder.Entity("Surasshu.Models.Quirk", b =>
                {
                    b.Property<int>("QuirkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuirkId"), 1L, 1);

                    b.Property<int?>("QuirkCost")
                        .HasColumnType("int");

                    b.Property<string>("QuirkDescription")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("QuirkName")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("QuirkId");

                    b.ToTable("Quirks");
                });

            modelBuilder.Entity("Surasshu.Models.Warrior", b =>
                {
                    b.Property<int>("WarriorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarriorId"), 1L, 1);

                    b.Property<int>("AttackMod")
                        .HasColumnType("int");

                    b.Property<int>("Crit")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("DieCount")
                        .HasColumnType("int");

                    b.Property<int>("DieSide")
                        .HasColumnType("int");

                    b.Property<int>("Hp")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool>("IsNinja")
                        .HasColumnType("bit");

                    b.Property<int?>("QuirkOneId")
                        .HasColumnType("int");

                    b.Property<int?>("QuirkThreeId")
                        .HasColumnType("int");

                    b.Property<int?>("QuirkTwoId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarriorName")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("WarriorId");

                    b.ToTable("Warriors");
                });

            modelBuilder.Entity("Surasshu.Models.WarriorTeam", b =>
                {
                    b.Property<int>("WarriorTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarriorTeamId"), 1L, 1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WarriorOneId")
                        .HasColumnType("int");

                    b.Property<int?>("WarriorThreeId")
                        .HasColumnType("int");

                    b.Property<int?>("WarriorTwoId")
                        .HasColumnType("int");

                    b.HasKey("WarriorTeamId");

                    b.ToTable("WarriorTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
